Modifying the terrafrom.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -52,19 +52,18 @@ jobs:
          run: terraform validate
 
        #- name: Terraform plan
-         id: plan
-         run: terraform plan -no-color -input=false -out planfile
-         continue-on-error: true
+        #  id: plan
+        #  run: terraform plan -no-color -input=false -out planfile
+        #  continue-on-error: true
 
       #- name: Terraform plan status
-         if: steps.plan.outcome == 'failure' 
-         run: exit 1 
+        #  if: steps.plan.outcome == 'failure' 
+        #  run: exit 1 
 
        - name: Terraform Apply
          id: apple
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-         run: terraform destroy -auto-approve -input=false -parallelism=1 planfile
-
+         run: terraform destroy -auto-approve 
        # #- name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v1
        #   with:
